# Generated by Django 5.0.11 on 2025-01-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_job_created_by_job_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated', '-posted']},
        ),
    ]
